"""Added note and is_note fields to DeliveryRecord

Revision ID: e35225570669
Revises: 89c1e3eda2d4
Create Date: 2025-04-05 18:49:32.164408

"""
from alembic import op
import sqlalchemy as sa

revision = 'e35225570669'
down_revision = '89c1e3eda2d4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_note', sa.Boolean(), nullable=False, server_default='0'))  # Добавили server_default
        batch_op.alter_column('description', existing_type=sa.VARCHAR(length=200), nullable=True)
        batch_op.alter_column('quantity', existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column('amount', existing_type=sa.FLOAT(), nullable=True)
        batch_op.alter_column('payment_type', existing_type=sa.VARCHAR(length=20), nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_record', schema=None) as batch_op:
        batch_op.alter_column('payment_type', existing_type=sa.VARCHAR(length=20), nullable=False)
        batch_op.alter_column('amount', existing_type=sa.FLOAT(), nullable=False)
        batch_op.alter_column('quantity', existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column('description', existing_type=sa.VARCHAR(length=200), nullable=False)
        batch_op.drop_column('is_note')
        batch_op.drop_column('note')
    # ### end Alembic commands ###
